name: Conditions
on: [push]

jobs: #pipeline
  terraform: #pipeline1
    runs-on: ubuntu-latest
    steps: #stages
      - name: checkout
        uses : actions/checkout@v5

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3.1.2 

      - name: run init
        run: terraform init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: run plan
        run: terrraform plan     